# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e65e33324d95cdca50109e0ce10e16ac6c8167ece61ba17abd56272d89700d21551eeaa65f18bb490950ed76066d0ac9c25025058779958d3da4e5bb6016ed2

test:
  secret_key_base: a690da794e867986f46e443c6fa6b912030a73f9f0bfd599e4a129393492f3a9e97b63eedf4a07ad0a0b54a374c5c1ff9473f405e7abf7bdafafbb535572b95b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
